name: Sync Game Config

on:
  push:
    paths:
      - "project.godot"
  pull_request:
    paths:
      - "project.godot"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: nu {0}

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: hustcer/setup-nu@v3
        with:
          version: "0.112.2"
          enable-plugins: true

      - name: Sync project.config.json
        run: |
          let project_config = open project.config.json
          $project_config
          | update name (open project.godot | from ini | get application?.'config/name'? | default $project_config.name)
          | update version (open project.godot | from ini | get application?.'config/version'? | default $project_config.version)
          | save -f project.config.json
          print "Updated project.config.json"

      - name: Commit and push if changed
        uses: iarekylew00t/verified-bot-commit@v2
        with:
          message: "update: sync project.config.json [skip ci]"
          files: |
            project.config.json
